#!/bin/bash
#S39wait4net.sh

#chmod +x S39wait4net.sh

#Maak daarvoor een script aan in de directory /etc/init.d in met de naam: S39wait4net.sh en maak deze executable.

#De inhoud van het script is als volgt:


i=1

echo -n "Wait for eth0 to initialize . ."

while :

do

   [ -d /sys/class/net/eth0 ] && break

   [ $i -eq 10 ] && echo " timeout." && exit 1

   echo -n " $i"

   sleep 1

   i=$(( $i + 1))

done

echo " OK."

#einde script
